[package]
name = "toy_ttf"
version = "0.1.0"
authors = ["AdnoC <adam.r.cutler@gmail.com>"]

[dependencies]
nom = "4.0"
num-traits = "0.2" # For num-derive
num-derive = {version = "0.2", features = ["full-syntax"]}

[dev-dependencies]
byte_conv = "0.1"
